name: Update Profile Readme With SO Answers
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install feedparser
    - name: Fetch RSS feed
      run: |
        ./fetch-rss.py
    - name: Generate readme
      run: |
        ./generate-readme.py
    - name: Commit changes
      run: |
        git config --global user.name "rukshan99"
        git config --global user.email "rukshanjayasekara@outlook.com"
        git commit -am "Update profile readme with latest Stack Overflow Answers"
